# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/disk_d/PythonProgs/CompGraph/Lab_1/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 659)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 110, 81, 31))
        self.lineEdit.setToolTipDuration(1)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 220, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 220, 81, 31))
        self.lineEdit_2.setToolTipDuration(1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 280, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(340, 280, 81, 31))
        self.lineEdit_3.setToolTipDuration(1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 340, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 390, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 390, 81, 31))
        self.lineEdit_4.setToolTipDuration(1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(90, 440, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(410, 440, 81, 31))
        self.lineEdit_5.setToolTipDuration(1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(530, 100, 191, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 220, 191, 91))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(530, 380, 191, 91))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 500, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 550, 301, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 550, 301, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторна робота №1"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>1)Параметри для основного елементу (квадрат):</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Довжина:"))
        self.lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>P.S. Рекомендований параметр: 20.</p><p>Не вводити числа менше 0 та більше 100!</p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>2)Параметри для орнаменту:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Кут повороту:"))
        self.lineEdit_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>P.S. Рекомендований параметр: 20.</p><p>Не вводити числа менше 0 та більше 100!</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Кількість вписаних квадратів:</p></body></html>"))
        self.lineEdit_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>P.S. Рекомендований параметр: 2.</p><p>Не вводити числа менше 0 та більше 3!</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>3)Параметри для спецефекту:</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Кількість елементів:</p></body></html>"))
        self.lineEdit_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>P.S. Рекомендований парметр: 5.</p><p>Не вводити числа менше 0 та більше 13!</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>Кількість вкладень кожного елемента:</p></body></html>"))
        self.lineEdit_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>P.S. Рекомендований парметр: 3.</p><p>Не вводити числа менше 0 та більше 3!</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Показати квадарт"))
        self.pushButton_2.setText(_translate("MainWindow", "Показати орнамент"))
        self.pushButton_3.setText(_translate("MainWindow", "Показати спецефект"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>4)Інші незмінювані орнамент та спецефект:</p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Орнамент"))
        self.pushButton_5.setText(_translate("MainWindow", "Спецефект"))

