# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 140, 511, 101))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 340, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 260, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 260, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(340, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setToolTipDuration(1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(440, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setToolTipDuration(1)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(430, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setToolTipDuration(1)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(290, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setToolTipDuration(1)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 340, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторна робота №4"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>1)Параметри a, b для поверхні:</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>2)Задайте межі зрізу х, у:</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>3)Тепер Ви можете переглянути таюлиці зрізу, грфіки,</p><p>гістограми та кругові діаграми, створені по </p><p>даним з цих таблиць:</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Показати кругові діаграми"))
        self.pushButton_4.setText(_translate("MainWindow", "Показати таблиці"))
        self.pushButton_5.setText(_translate("MainWindow", "Показати графіки"))
        self.lineEdit_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>P.S. Рекомендований параметр: 20.</p><p>Не вводити числа менше 0 та більше 100!</p><p><br/></p></body></html>"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "1"))
        self.lineEdit_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>P.S. Рекомендований параметр: 20.</p><p>Не вводити числа менше 0 та більше 100!</p><p><br/></p></body></html>"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "1"))
        self.lineEdit_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>P.S. Рекомендований параметр: 20.</p><p>Не вводити числа менше 0 та більше 100!</p><p><br/></p></body></html>"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "від -10 до 10"))
        self.lineEdit_9.setToolTip(_translate("MainWindow", "<html><head/><body><p>P.S. Рекомендований параметр: 20.</p><p>Не вводити числа менше 0 та більше 100!</p><p><br/></p></body></html>"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "від -10 до 10"))
        self.pushButton_6.setText(_translate("MainWindow", "Показати гістограми"))

